version: "3"

services:
  proxy-manager:
    image: shellus/proxy-manager
    build: .
    volumes:
      - ./mysql:/var/lib/mysql
      - ./acme.sh:/acme.sh
      - /Users/shellus/www/proxy-manager:/webroot/proxy-manager
    ports:
      - "80:80"
      - "443:443"
      - "3309:3306"
