version: "3"

services:
  proxy-manager:
    image: shellus/proxy-manager
    build: .
    volumes:
      - ./mysql:/var/lib/mysql
      - ./vhost:/etc/nginx/sites-enabled
      - /mnt/www/me/proxy-manager:/webroot/proxy-manager
    ports:
      - "80:80"
      - "443:443"
