version: "3"

services:
  proxy-manager:
    image: shellus/proxy-manager
    build: .
    volumes:
      - ./config:/config
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nginx_net
networks:
  nginx_net:
    external: true
